language: node_js
sudo: false
node_js:
- '7'

branches:
  only:
  - master

script: 
  - npm install -g hexo
  - hexo deploy

env:
  global:
    secure: P62s73xico3bijgJLcfBxzAIwhMkljbT+PXm/Gq80X+7a/Kvq/g/KJOVuvQAIJi+3m3Mo2DUG4jXCQIhXq48BLV5cK9IechuuDjGXZR0IRSfNPqhEBQPdtVe9ixbFv/FsMErXee0ju2nhsXcm0EmzimYQ/NTLVxyRTkCsSCIs3wxelXj7+mrUC8R+sRD+GttaPuIHLT6hpUCW02qhmzIaOhMzTQppxZwVN/ffcxtCs3JH1bHfxnU+C1GAv5a0dASGiRwxaD/RD3tdF3HcYTx/cSwDejNRAKSTmWbER8OuofMb2thssjglORxUiJf9wck2ft+f1MFrCmNjltPfIROIkeI/l6EOUydcax7OC5TJA9137GsgNOFPBW/d96JXAnAge60TFVbkfhZhn8D68hDHmILw6BQuWU891QzeBYma8/BRWDz+Fs5bVWNl+DOZ9d76g6tUunjDPjgRrwymcdbrzlfxnrAUiGc/AP8YCCRaSezLVUYbQEsoITdpMZI4RXG/JU9dunInNIet2vID0p9B6KqKUXqOmKbg75qhV84hxTcChd2AME6ll43aarRwmLvWyIJevkVmS6zJUZiEXxQkpXD4d9y1B2XqHDR6dW80UYqrDyiEM3wTNhBAkaExToe2xmfQ0yNHvTaAmd+ZL76n3YfvPFg0iUY2ETAhcg+UXE=
