language: node_js
sudo: false
node_js:
- '7'

install: npm install -g hexo
script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git remote remove origin
- git remote add origin https://${GH_TOKEN}:@github.com/GoContainer/gocontainer.fr.git
- npm install && hexo deploy