language: node_js
sudo: false

node_js:
- '7'

cache:
  apt: true
  directories:
  - node_modules

env:
  global:
    secure: PNPYbXIxX/x4fEPXOf3FIor4sMMbFyqDG434h3YlfgSR8efVUJHoVwk0DGLi3H1qBWn/NFqkLXmWmM05F+rovqibugBV48uindALBy5tUhS7qJNWudn1pLK4CD4WfpgB7Vem2QcNvtFT0tmTVnS9fogsaQAGQ476vVKVyo4BoXn/MaJ9xZFGUv24boNJIwNidfmntIZejlKg7JkqAf8TXgMNSVU/1SUU4IUcnUruwZzPTvMGfmBvfZFB9UcvqrN3WD2q56d15Xj+iZ4NNW5uakMpNZZL0PlmcPS3PHL/z6y51xM/jPT/G0J1zPDVxUaDWze4SKzZ2FHj19/+Ldo2dErefyUWwX8VtcnHBxR1uKRcr1Gt6roX2+pBgOljU15vHGrJJqTYUirbEIlsmXeBPxZWMvLeSuLWIhkw6Qva7/vUGE/C6YIvn/pa7hWf/5fWGT7Diapyi8+8Bhn4IOxIIUecbfhC1rQX13qGZ9X0za7HcjCXKquQHcyXC2498D+v2sewgtq1IiTiEbx+Df5v/a9QqT2/+ZLynu/SFjg4Dl/yw1WjoC6YfVl6VS8K9D3TaTXwHVNBMCcoRYx7SeLHhYDnbZnzV1YlfdOU1x7HEa7nTJ9RKZA3rvkpSwCkOuL12U6dUQa8um9wMhLhOcUb0OssiQVO23B7eVrmFF2EbSQ=


before_install:
- npm install -g hexo
- npm install

deploy:
  skip_cleanup: true
  provider: script
  script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git remote remove origin
  - git remote add origin https://${GH_TOKEN}:@github.com/datacubeio/docs.git
  - hexo deploy
  on:
    branch: master