language: node_js

node_js:
- "6"

before_install:
- npm install -g hexo

install:
- npm install

before_script:
- git config --global user.name 'Travis'
- git config --global user.email 'travis@travis-ci.org'

# Maybe add minification scripts here
script:
- hexo generate

after_success:
- mkdir .deploy                   # Create a folder to use for teh pages branch
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add origin $DEPLOY_REPO)
- git init && git remote add origin https://$GH_TOKEN@github.com/GoContainer/gocontainer.fr.git
- rm -rf ./*                      # Clear old verion
- cp -r ../public/* .             # Copy over files for new version
- git add -A .          
- git commit -m 'Site updated wich Travis'    # Make a new commit for new version
- git branch -m gh-pages
- git push -q -u origin gh-pages --force  # Push silently so we don't leak information