baseurl: http://gocontainer.fr/
disqusShortname: spf13
footnotereturnlinkcontents: ↩
googleAnalytics: ''
languageCode: fr-fr
paginate: 10
params:
  author: Go Container
  avatar: css/images/avatar.png
  bio: Blog
  copyright: Go Container - © Copyright
  custom_css: []
  custom_js: []
  date_format: '2006-01-02'
  disable_mathjax: false
  logo: css/images/logo.png
  menu:
  - before: true
    label: Home
    link: /
  - before: false
    label: Categories
    link: categories/
  profile:
    follow_button: https://github.com/digitalcraftsman
  site_description: ''
  widgets:
    categories: true
    recent_articles: true
    tag_cloud: true
    tags: true
permalinks:
  post: /:year/:month/:day/:slug

theme: gocontainer
title: Go Container
